order: 7
variants:
- name: info
  context:
    label: Info
    mod: info
- name: attention
  context:
    label: Attention
    mod: attention
- name: warning
  context:
    label: Warning
    mod: warning
- name: alert
  context:
    label: Alert
    mod: alert
- name: severe
  context:
    label: Severe
    mod: severe
- name: error
  context:
    label: Error
    mod: error
- name: muted
  context:
    label: Muted
    mod: muted
- name: compact
  context:
    label: Compact
    mod: compact
